spring.application.name=EurekaServer
server.port=8761
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://${INFRA_HOST}:9411/api/v2/spans