spring.application.name=UserService
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/omnipoint_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create

jwt.secret-key=ASKJDbakjASDLnln@#123
jwt.lifetime=24h