spring.application.name=UserService
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5435/users_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create

spring.kafka.bootstrap-servers=localhost:9092
kafka.topics.user-created=user_created

jwt.secret-key=2mbvVpKfhGXap2jJ8xoNyl6rqBeCsSp7DSFotGWeQII
jwt.lifetime=24h

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.enabled=false