spring.application.name=UserService
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5435/users_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create

spring.kafka.bootstrap-servers=localhost:9092
kafka.topics.get-user-status=get_user_status

jwt.secret-key=5Kj8mN2pQ7rT9vW1xY4zA6bC3dE0fG8hI5jK2lM7nO9pR1sT4uV6wX8yZ0aB3cD5
jwt.lifetime=24h

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true