spring.application.name=wallet-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5434/wallet_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create

spring.kafka.bootstrap-servers=localhost:9092
kafka.topics.points-calculated=points_calculated
kafka.topics.user-created=user_created
kafka.topics.transaction-handled=transaction_handled
kafka.topics.points-failed=points_failed

kafka.topics.dlq-suffix=.DLQ

jwt.secret-key=2mbvVpKfhGXap2jJ8xoNyl6rqBeCsSp7DSFotGWeQII

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true