spring.application.name= RuleEngineService
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ruleEngine_db
spring.datasource.password=admin
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=create

spring.kafka.bootstrap-servers=localhost:9092
