spring.application.name=gateway-service
server.port=8080

jwt.secret-key=2mbvVpKfhGXap2jJ8xoNyl6rqBeCsSp7DSFotGWeQII

spring.data.redis.host=${INFRA_HOST:redis}
spring.data.redis.port=6379

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://${INFRA_HOST}:9411/api/v2/spans

management.endpoints.web.exposure.include=health,prometheus

#USER SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/users, /api/v1/users/**

#CIRCUIT BREAKER
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.name=userCircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.fallbackUri=forward:/fallback
#RATE LIMITER
spring.cloud.gateway.server.webflux.routes[0].filters[1].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.burstCapacity=20
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.key-resolver=#{@keyResolver}

#TRANSACTION SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=transaction-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/transactions, /api/v1/transactions/**

#CIRCUIT BREAKER
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=transactionCircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/fallback
#RATE LIMITER
spring.cloud.gateway.server.webflux.routes[1].filters[1].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.redis-rate-limiter.burstCapacity=20
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.key-resolver=#{@keyResolver}

#WALLET SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=wallet-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://WALLET-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/wallets, /api/v1/wallets/**

#CIRCUIT BREAKER
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.name=walletCircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.fallbackUri=forward:/fallback

#RULE ENGINE SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=rule-engine-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://RULE-ENGINE-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/rules, /api/v1/rules/**

#CIRCUIT BREAKER
spring.cloud.gateway.server.webflux.routes[3].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.name=ruleEngineCircuitBreaker
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.fallbackUri=forward:/fallback

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*

spring.cloud.gateway.server.webflux.httpclient.connect-timeout=3000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=4000