spring.application.name=gateway-service
server.port=8080

jwt.secret-key=2mbvVpKfhGXap2jJ8xoNyl6rqBeCsSp7DSFotGWeQII

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://${INFRA_HOST}:9411/api/v2/spans

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webflux.routes[1].id=transaction-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/transactions/**

spring.cloud.gateway.server.webflux.routes[2].id=wallet-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://WALLET-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/wallets/**

spring.cloud.gateway.server.webflux.routes[3].id=rule-engine-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://RULE-ENGINE-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/rules/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*